spring.application.name=pagos
spring.datasource.url=jdbc:postgresql://localhost:5432/conciliacion
spring.datasource.username=conciliacion
spring.datasource.password=conciliacion
spring.flyway.locations=classpath:db/migration,classpath:db/seed